version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/.build
    env_file:
      - .env
    # command: .build/debug/YourSwiftApp
    command: bash
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      PORT: 8080
    networks:
      - mail-net
    tty: true

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
      args:
        - INIT_PATH=./db/init/*
        - CONFIG_FILE_PATH=./db/postgres.conf
    env_file:
      - .env
    environment:
      - POSTGRES_INITDB_ARGS="--locale-provider=icu --locale=en_US.utf8 --icu-locale=en --config_file=/etc/postgres/postgres.conf"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      mail-net:
        aliases:
          - postgresdb

volumes:
  postgres-data:


networks:
  mail-net:
    driver: bridge
